#! /bin/bash
#SBATCH --qos=short
#SBATCH --job-name=gridding
#SBATCH --account=anthroia
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --mail-type=REQUEUE
#SBATCH --mail-user=robinson@pik-potsdam.de
#SBATCH --output=out.out
#SBATCH --error=out.err
#SBATCH --time=10:00:00

# Run the job
./gridder.x 



##SBATCH --partition=ram_gpu
##SBATCH --mem=50000 
