#! /bin/bash
#SBATCH --qos=priority
#SBATCH --job-name=gridding
#SBATCH --account=anthroia
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --mail-type=REQUEUE
#SBATCH --mail-user=robinson@pik-potsdam.de
#SBATCH --output=out.out
#SBATCH --error=out.err
#SBATCH --time=2:00:00
#SBATCH --mem=50000 
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --cpus-per-task=16

export OMP_PROC_BIND=true  # make sure our threads stick to cores
export OMP_NUM_THREADS=16  # matches how many cpus-per-task we asked for
export OMP_NESTED=false
export OMP_STACKSIZE=64M


# Run the job
./gridder_pmip3.x 



##SBATCH --partition=ram_gpu
##SBATCH --mem=50000 
