#! /bin/bash
#SBATCH --qos=priority
#SBATCH --job-name=era5
#SBATCH --account=anthroia
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --mail-type=REQUEUE
#SBATCH --mail-user=robinson@pik-potsdam.de
#SBATCH --output=out.out
#SBATCH --error=out.err
#SBATCH --time=0:01:00
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --cpus-per-task=1

# Run the job
python get-era5-hourly-local.py YEARNOW 

